In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
b=np.array([[1,2,3],[4,5,6]])

In [5]:
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [7]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
d=np.array([1,2,4,6],dtype=float)

In [9]:
d

array([1., 2., 4., 6.])

In [10]:
d=np.array([1,2,4,6],dtype=bool)

In [11]:
d

array([ True,  True,  True,  True])

In [12]:
d=np.array([1,2,4,6],dtype=complex)

In [13]:
d

array([1.+0.j, 2.+0.j, 4.+0.j, 6.+0.j])

# arange()

In [14]:
e=np.arange(1,21)

In [15]:
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
f=np.arange(1,20,2)

In [17]:
print(f)

[ 1  3  5  7  9 11 13 15 17 19]


# reshape()

In [18]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
e.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
e.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# ones() function

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# zeros()

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# empty()

In [23]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# eye() --> this fuction is used to create an array having all the diagonal elements is one. 

In [24]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# linspace()

this function is used to find the random numbers bwtween  two numbers. and the difference between two any points will be same 

In [25]:
np.linspace(10,30,10)

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

# identity()

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ARRAY ATTRIBUTES

In [27]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [28]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim 

ndim is used to find the dimension of an array

In [29]:
a1.ndim

1

In [30]:
a2.ndim

2

In [31]:
a3.ndim

3

# shape

# this attributes shows the shape of an array

In [32]:
a1.shape

(10,)

In [33]:
a2.shape

(3, 4)

In [34]:
a3.shape

(2, 2, 2)

# size

it gives the number of items in the array

In [35]:
a3.size

8

In [36]:
a2.size

12

In [37]:
a1.size

10

# itemsize

# it will give the memory size of the array

In [38]:
a1.itemsize

4

In [39]:
a2.itemsize

8

In [40]:
a3.itemsize

4

# dtype

In [41]:
a1.dtype

dtype('int32')

In [42]:
a2.dtype

dtype('float64')

In [43]:
a3.dtype

dtype('int32')

# changing datatypes

In [44]:
a3.dtype

dtype('int32')

In [45]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# ARRAY OPERATION

In [46]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [47]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
#scalar operations
#relational operator
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
#relational 
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
a2>50

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# array function

In [54]:
a1=np.random.random((3,3))
a1=np.round(a1*100)

In [55]:
a1

array([[49., 17., 80.],
       [23., 87., 28.],
       [58., 22., 96.]])

# min/max/sum/prod in numpy

In [56]:
np.min(a1)

17.0

In [57]:
np.max(a1)

96.0

In [58]:
np.sum(a1)

460.0

In [59]:
np.prod(a1)

457364040376320.0

# if we want to apply this fuction column wise or row wise
axis=0 --> col axis=1--> row

In [60]:
np.max(a1,axis=1)

array([80., 87., 96.])

In [61]:
np.min(a1,axis=1)

array([17., 23., 22.])

In [62]:
np.sum(a1,axis=1)

array([146., 138., 176.])

In [63]:
np.product(a1,axis=1)

array([ 66640.,  56028., 122496.])

# mean/median/var/std


In [64]:
np.mean(a1)

51.111111111111114

In [65]:
np.mean(a1,axis=1)

array([48.66666667, 46.        , 58.66666667])

In [66]:
np.median(a1)

49.0

In [67]:
np.var(a1)

836.0987654320987

In [68]:
np.std(a1)

28.915372476108598

# trigonometric function

In [69]:
np.sin(a1)

array([[-0.95375265, -0.96139749, -0.99388865],
       [-0.8462204 , -0.82181784,  0.27090579],
       [ 0.99287265, -0.00885131,  0.98358775]])

In [70]:
np.sin(45)

0.8509035245341184

# dot product

In [71]:
a2=np.arange(12).reshape(3,4)

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a3=np.arange(12,24).reshape(4,3)

In [74]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [75]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log and exponent

In [76]:
np.log(a1)

array([[3.8918203 , 2.83321334, 4.38202663],
       [3.13549422, 4.46590812, 3.33220451],
       [4.06044301, 3.09104245, 4.56434819]])

In [77]:
np.exp(a1)

array([[1.90734657e+21, 2.41549528e+07, 5.54062238e+34],
       [9.74480345e+09, 6.07603023e+37, 1.44625706e+12],
       [1.54553894e+25, 3.58491285e+09, 4.92345829e+41]])

# round/floor/cell

In [78]:
a=np.random.random((3,3))*100

In [79]:
a

array([[55.18402424, 18.92811593, 84.86806898],
       [96.88285655, 27.26979578,  8.52386008],
       [86.40309744, 74.18410547, 72.33630978]])

In [80]:
np.round(a)

array([[55., 19., 85.],
       [97., 27.,  9.],
       [86., 74., 72.]])

In [81]:
np.floor(a)

array([[55., 18., 84.],
       [96., 27.,  8.],
       [86., 74., 72.]])

In [82]:
np.ceil(a)

array([[56., 19., 85.],
       [97., 28.,  9.],
       [87., 75., 73.]])

# indexing and slicing

In [83]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a1[-1]

9

In [86]:
a1[0]

0

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# if we want to find a particular number from the given arrays we will have to give the first row number and second column number. 

In [88]:
a2[1,2]

6

In [89]:
a2[2,3]

11

In [90]:
a2[1,0]

4

# now working with 3D array

indexing --> in this, we find a single number at a time

In [91]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
a3[1,0,1]

5

In [93]:
a3[0,1,0]

2

In [94]:
a3[0,0,0]

0

In [95]:
a3[1,1,0]

6

# slicing we find the multiple elements at a time


In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a1[2:5]

array([2, 3, 4])

In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
#want to find the first row
a2[0,:]

array([0, 1, 2, 3])

In [100]:
#want to find 3rd column
a2[:,2]

array([ 2,  6, 10])

In [101]:
# want to find 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [102]:
# want to find 0,3,8,11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [103]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [104]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a2[1,0::3]

array([4, 7])

In [106]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [107]:
a3=np.arange(27).reshape(3,3,3)

In [108]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [110]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [111]:
a3[0,1]

array([3, 4, 5])

In [112]:
a3[1,:,1]

array([10, 13, 16])

In [113]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [114]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[0,0,0::2]

array([0, 2])

In [116]:
a3[2,0,0::2]

array([18, 20])

In [117]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# ITERATING

In [118]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [121]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [122]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [123]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [124]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# transpose

In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# ravel:- it used to convert the n-dimension array into the one dimensional array.

In [127]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [129]:
#horizontal stack
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [130]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [131]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# spliting

In [132]:
#horizontal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [134]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [135]:
#vertical spliting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]