# CREATING RANDOM NUMBERS

# (1) RAND()

In [6]:
import numpy as np

var=np.random.rand(4)
print(var)

[0.08648433 0.18977911 0.10253374 0.23942957]


In [8]:
var1=np.random.rand(4,5)
print(var1)

[[0.41392071 0.12826469 0.59137414 0.19854264 0.16800302]
 [0.03466033 0.17849742 0.86926946 0.9460045  0.53074424]
 [0.34323316 0.1487158  0.66361778 0.45023047 0.16882887]
 [0.82216262 0.59430407 0.22584458 0.03554681 0.9877333 ]]


# (2) randn()

In [11]:
import numpy as np

var3=np.random.randn(7)
print(var3)

[ 0.75653325  1.56214105 -1.1215292   0.7333373   0.26963546  0.36299089
 -1.62519417]


In [12]:
var4=np.random.randn(5,7)
print(var4)

[[-0.8268105  -0.40434435 -0.42500237  0.54251375 -0.77479136  1.93695287
   0.65600141]
 [-0.6710117  -0.36231782  0.15624239  0.19885461  0.85993411  0.10528097
  -1.32320372]
 [ 0.8917937  -0.58812792 -0.29509501  0.18567586 -1.32056678 -1.6140772
   1.62235391]
 [-0.11209284 -0.93328813 -0.43776853  0.53102192 -1.42857323  1.42300411
   0.06655336]
 [-1.16218485 -1.88681183  0.46342688 -1.01260246  0.37500163 -0.12696881
   0.59927479]]


# (3) ranf()

In [13]:
import numpy as np

var5=np.random.ranf(7)
print(var5)

[0.04960249 0.89836299 0.77685182 0.33901914 0.19570738 0.52452033
 0.01261327]


In [14]:
var6=np.random.ranf(3,4)
print(var6)

TypeError: random_sample() takes at most 1 positional argument (2 given)

# (4) randint()

In [15]:
import numpy as np

var7=np.random.randint(7)
print(var7)

0


In [16]:
import numpy as np

var8=np.random.randint(7,40,500)
print(var8)

[ 9 30 26  9 18 16 31 16 17 29 37 29 25 20 19 20 10  9 17 10 29 32 25 15
 21 16 36 11 36 33 38 13 15  7  7  7 35  8 22 26  9 15 31 21 30 20 17  7
 20 25 17  9 37 34 11 25 33 35 25 10 18 27 21 18 13 34 28 30 33 35 20 22
 26 39  8 27 12 13 25 15 32 16 23 36 12 11 18 30 12 10 33 31 28 22 12 34
 16 26 26 28 23 18 30 24  7 28 22  7 39 34 25 11  9 33 32 32 26 12 21  8
 31 27 23 17 25 31 33 34 17 27 24 11 33 21 30 18 19 13 14 28 37 22 37 33
 29 15 23 29 25 29 37  7 25 24 32 11 32 28  8 29 13 24 13 26 24 20 30 36
 28 23 22 17 10 12 37  7 32 25 10 39 31 26  9 11 17 30 20 29 33 35 11 20
 24 20 12 18 23 22 16 19 39 25 19 39 31 28 37 32 36 18 15 33 33 21 21 19
 18  9 26 24 22 37 38  8 14 14 22 23 29 30 33 31 16 36 28 10 11 13 34 26
  7 12 30 12 32  7 27 28 28  8 21 34 38 23 15 10 10 13 34 28  8 20 31 18
 38 13 25 17 32  8 32 22  9 34 26 13 10 25 27 10  8 17 39 25 30 31 23 37
 21 27 27 13 14 32 29 28 11 33 24  8 22 31 33 30 35 12 24  7 36 28 39 23
 16 31 12 17  9 23 23 16 11 31 24 25 18 24 37  7 36

# DATA TYPES IN NUMPY

In [18]:
import numpy as np
var9=np.array([2,4,5,6])
print("data type is",var9.dtype)

data type is int32


In [19]:
import numpy as np
var10=np.array([2.6,4.4,5.7,6.9])
print("data type is",var10.dtype)

data type is float64


In [20]:
import numpy as np
var11=np.array(["A","B","C","D"])
print("data type is",var11.dtype)

data type is <U1


In [21]:
import numpy as np
var12=np.array(["A","B","C","D",1,2,3,4])
print("data type is",var12.dtype)

data type is <U11


In [24]:
x=np.array([1,2,3,4])
print(x.dtype)
print(x)

int32
[1 2 3 4]


# converting this data type into the the int8

In [25]:
y=np.array([1,2,3,4],dtype=np.int8)
print(y.dtype)
print(y)

int8
[1 2 3 4]


In [26]:
z=np.array([1,2,3,4],dtype="f")
print(z.dtype)
print(z)


float32
[1. 2. 3. 4.]


# SHAPE

In [29]:
import numpy as np
a=np.array([[2,4,1,3],[5,6,7,8]])
print(a)
print()
print(a.shape)

[[2 4 1 3]
 [5 6 7 8]]

(2, 4)


In [30]:
b=np.array([1,3,4,6],ndmin=4)
print(b)


[[[[1 3 4 6]]]]


# RESHAPE

In [32]:
import numpy as np
c=np.array([1,2,3,4,5,6])
x=c.reshape(3,2)
print(c)
print(x)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [34]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=c.reshape(3,2,2)
print(c)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [35]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=c.reshape(3,2,2)
z=x.reshape(-1)
print(c)
print()
print(x)
print()
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# ARITHMETIC OPERATION USING NUMPY

In [36]:
import numpy as np
var=np.array([1,3,4,5])
var1=var+3
print(var1)


[4 6 7 8]


In [37]:
import numpy as np
var2=np.array([1,3,4,5])
var3=np.array([4,5,6,7])
var4=var2 + var3
print(var4)


[ 5  8 10 12]


In [44]:
import numpy as np
var2=np.array([1,3,4,5])
var3=np.array([4,5,6,7])
var4=np.add(var2,var3)
print(var4)


[ 5  8 10 12]


In [38]:
import numpy as np
var=np.array([1,3,4,5])
var1=var-3
print(var1)


[-2  0  1  2]


In [39]:
import numpy as np
var2=np.array([1,3,4,5])
var3=np.array([4,5,6,7])
var4=var2 - var3
print(var4)


[-3 -2 -2 -2]


In [40]:
import numpy as np
var2=np.array([1,3,4,5])
var3=np.array([4,5,6,7])
var4=var2 * var3
print(var4)


[ 4 15 24 35]


In [41]:
import numpy as np
var=np.array([1,3,4,5])
var1=var*3
print(var1)


[ 3  9 12 15]


In [42]:
import numpy as np
var=np.array([1,3,4,5])
var1=var/3
print(var1)


[0.33333333 1.         1.33333333 1.66666667]


In [43]:
import numpy as np
var=np.array([1,3,4,5])
var1=var%3
print(var1)


[1 0 1 2]


In [45]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.array([[9,10,11,12],[1,6,7,8]])
print(var2)
print()
print(var3)
print()
var4=var2+var3
print(var4)


[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [ 1  6  7  8]]

[[10 12 14 16]
 [ 6 12 14 16]]


In [46]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.array([[9,10,11,12],[1,6,7,8]])
print(var2)
print()
print(var3)
print()
var4=var2-var3
print(var4)

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [ 1  6  7  8]]

[[-8 -8 -8 -8]
 [ 4  0  0  0]]


In [47]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.array([[9,10,11,12],[1,6,7,8]])
print(var2)
print()
print(var3)
print()
var4=var2*var3
print(var4)

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [ 1  6  7  8]]

[[ 9 20 33 48]
 [ 5 36 49 64]]


# ARITHMETIC FUNCTION

In [58]:
import numpy as np
var=np.array([1,3,4,5])
print("minimum value is", np.min(var),np.argmin(var))
print("maximum value is", np.max(var),np.argmax(var))
print("square root is", np.sqrt(var))


minimum value is 1 0
maximum value is 5 3
square root is [1.         1.73205081 2.         2.23606798]


In [54]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.min(var2,axis=1)
print(var3)

[1 5]


In [55]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.min(var2,axis=0)
print(var3)

[1 2 3 4]


In [56]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.max(var2,axis=1)
print(var3)

[4 8]


In [57]:
var2=np.array([[1,2,3,4],[5,6,7,8]])
var3=np.max(var2,axis=0)
print(var3)

[5 6 7 8]


In [59]:
var=np.array([1,3,4,5])
print("sin value is",np.sin(var))

sin value is [ 0.84147098  0.14112001 -0.7568025  -0.95892427]


In [60]:
var=np.array([1,3,4,5])
print("sin value is",np.cos(var))

sin value is [ 0.54030231 -0.9899925  -0.65364362  0.28366219]


In [62]:
var=np.array([1,3,4,5])
print("cummulative sum is",np.cumsum(var))

cummulative sum is [ 1  4  8 13]
