In [1]:
import numpy as np

# np.sort

In [2]:
a=np.random.randint(1,200,15)
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [3]:
b=np.random.randint(50,100,24).reshape(6,4)
b

array([[88, 75, 54, 73],
       [79, 88, 97, 84],
       [60, 55, 65, 96],
       [58, 71, 61, 88],
       [88, 70, 91, 58],
       [99, 57, 99, 87]])

In [4]:
np.sort(a)

array([ 16,  17,  21,  41,  43,  78,  80,  83, 113, 130, 135, 138, 163,
       171, 180])

In [5]:
#descending order
np.sort(a)[::-1]

array([180, 171, 163, 138, 135, 130, 113,  83,  80,  78,  43,  41,  21,
        17,  16])

In [6]:
#row wise sorting
np.sort(b)

array([[54, 73, 75, 88],
       [79, 84, 88, 97],
       [55, 60, 65, 96],
       [58, 61, 71, 88],
       [58, 70, 88, 91],
       [57, 87, 99, 99]])

In [7]:
#column wise
np.sort(b,axis=0)

array([[58, 55, 54, 58],
       [60, 57, 61, 73],
       [79, 70, 65, 84],
       [88, 71, 91, 87],
       [88, 75, 97, 88],
       [99, 88, 99, 96]])

# np.append

this function is used to insert the values in the last of an array.

In [8]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [9]:
np.append(a,200)

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17, 200])

In [10]:
b

array([[88, 75, 54, 73],
       [79, 88, 97, 84],
       [60, 55, 65, 96],
       [58, 71, 61, 88],
       [88, 70, 91, 58],
       [99, 57, 99, 87]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[88., 75., 54., 73.,  1.],
       [79., 88., 97., 84.,  1.],
       [60., 55., 65., 96.,  1.],
       [58., 71., 61., 88.,  1.],
       [88., 70., 91., 58.,  1.],
       [99., 57., 99., 87.,  1.]])

# np.concatenate()

In [12]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

In [13]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique()

In [17]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6,])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims()

In [18]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where()

In [21]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [22]:
#find all indeces with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  5,  7,  8,  9, 11, 12, 13], dtype=int64),)

In [23]:
#replace all value > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 41,  0, 21,  0, 16,  0,  0,  0, 43,  0,  0,  0, 17])

In [24]:
np.where(a%2==0,0,a)

array([  0,   0,  41,   0,  21, 135,   0,   0,  83, 113,  43, 171, 163,
         0,  17])

# np.argmax()

In [25]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [26]:
np.argmax(a)

7

In [27]:
b

array([[88, 75, 54, 73],
       [79, 88, 97, 84],
       [60, 55, 65, 96],
       [58, 71, 61, 88],
       [88, 70, 91, 58],
       [99, 57, 99, 87]])

In [28]:
np.argmax(b,axis=1)

array([0, 2, 3, 3, 2, 0], dtype=int64)

# np.argmin()

In [29]:
np.argmin(a)

6

# np.cumsum()

In [30]:
np.cumsum(a)

array([ 138,  218,  259,  389,  410,  545,  561,  741,  824,  937,  980,
       1151, 1314, 1392, 1409], dtype=int32)

In [31]:
b

array([[88, 75, 54, 73],
       [79, 88, 97, 84],
       [60, 55, 65, 96],
       [58, 71, 61, 88],
       [88, 70, 91, 58],
       [99, 57, 99, 87]])

In [32]:
np.cumsum(b)

array([  88,  163,  217,  290,  369,  457,  554,  638,  698,  753,  818,
        914,  972, 1043, 1104, 1192, 1280, 1350, 1441, 1499, 1598, 1655,
       1754, 1841], dtype=int32)

In [33]:
np.cumsum(b,axis=0)

array([[ 88,  75,  54,  73],
       [167, 163, 151, 157],
       [227, 218, 216, 253],
       [285, 289, 277, 341],
       [373, 359, 368, 399],
       [472, 416, 467, 486]], dtype=int32)

# np.cumprod()

In [34]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [35]:
np.cumprod(a)

array([        138,       11040,      452640,    58843200,  1235707200,
        -683252544,  1952861184,  -672305152,    33247232,  -538030080,
       -1660456960,  -470298624,   650735616,  -782229504,  -412999680],
      dtype=int32)

# np.percentile()

In [36]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [37]:
np.percentile(a,100)

180.0

In [38]:
np.percentile(a,0)

16.0

In [39]:
np.percentile(a,50)

83.0

# np.hitogram()

In [40]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [41]:
np.histogram(a,bins=[20,40,60,80,100,120,140,160,180,200])

(array([1, 2, 1, 2, 1, 3, 0, 2, 1], dtype=int64),
 array([ 20,  40,  60,  80, 100, 120, 140, 160, 180, 200]))

# np.corrcoef()

In [42]:
np.corrcoef(a)

1.0

In [43]:
salary=np.array([2000,40000,400000,30000])
experience=np.array([1,3,12,5])

In [44]:
np.corrcoef(salary,experience)

array([[1.        , 0.95726401],
       [0.95726401, 1.        ]])

# np.isin()

In [45]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [46]:
item=[20,58,99,191,44,45,150]
np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [47]:
a[np.isin(a,item)]

array([], dtype=int32)

# np.flip()

In [48]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [49]:
np.flip(a)

array([ 17,  78, 163, 171,  43, 113,  83, 180,  16, 135,  21, 130,  41,
        80, 138])

In [50]:
b

array([[88, 75, 54, 73],
       [79, 88, 97, 84],
       [60, 55, 65, 96],
       [58, 71, 61, 88],
       [88, 70, 91, 58],
       [99, 57, 99, 87]])

In [51]:
np.flip(b,axis=0)

array([[99, 57, 99, 87],
       [88, 70, 91, 58],
       [58, 71, 61, 88],
       [60, 55, 65, 96],
       [79, 88, 97, 84],
       [88, 75, 54, 73]])

# np.put()

In [52]:
a

array([138,  80,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [53]:
np.put(a,[0,1],[110,530])

In [54]:
a

array([110, 530,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

put() is used for the putting new item in the existing places.

# np.delete()

In [55]:
a

array([110, 530,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [56]:
np.delete(a,0)

array([530,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,  78,
        17])

In [57]:
np.delete(a,[0,3,4])

array([530,  41, 135,  16, 180,  83, 113,  43, 171, 163,  78,  17])

# set functions

1. np.union1d()

In [58]:
m=np.array([3,4,5,6,7,8])
n=np.array([1,2,3,4,5,6])

In [59]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

# 2. np.intersect1d()

In [60]:
np.intersect1d(m,n)

array([3, 4, 5, 6])

# 3. np.setdiff1d()

In [61]:
np.setdiff1d(m,n)

array([7, 8])

# 4. np.setxor1d()

In [62]:
np.setxor1d(m,n)

array([1, 2, 7, 8])

# 5. np.in1d()

In [63]:
np.in1d(m,4)

array([False,  True, False, False, False, False])

# np.clip()

In [64]:
a

array([110, 530,  41, 130,  21, 135,  16, 180,  83, 113,  43, 171, 163,
        78,  17])

In [65]:
np.clip(a,a_min=1,a_max=100)

array([100, 100,  41, 100,  21, 100,  16, 100,  83, 100,  43, 100, 100,
        78,  17])

by this function we can clip the values in the given range